/**
 * Precios y limites del plan (negocio + markup Sonnet).
 * @readonly
 */
module.exports = {
  INCLUDED_PLAN_PRICE_USD: 15,
  INCLUDED_TOKENS_LIMIT: 3_000_000,
  INCLUDED_ALERT_THRESHOLD_PERCENT: 80,

  SONNET_INPUT_PRICE_PER_1M: 6,
  SONNET_OUTPUT_PRICE_PER_1M: 30,
  SONNET_PROVIDER_INPUT_COST_PER_1M: 3,
  SONNET_PROVIDER_OUTPUT_COST_PER_1M: 15,
};
